//! Mental model persistence — generated by the reflect engine.
//!
//! Mental models are markdown files stored in `~/.clearmemory/mental_models/`.
//! Each model captures a synthesized view of a topic across multiple memories.

use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// A synthesized mental model on a specific topic.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MentalModel {
    pub topic: String,
    pub content: String,
    pub updated_at: DateTime<Utc>,
}

/// Save a mental model as a markdown file in the given directory.
///
/// The filename is derived from the topic by replacing non-alphanumeric
/// characters with hyphens.
pub fn save_mental_model(dir: &Path, model: &MentalModel) -> Result<()> {
    std::fs::create_dir_all(dir).context("failed to create mental_models directory")?;

    let filename = topic_to_filename(&model.topic);
    let path = dir.join(format!("{filename}.md"));

    let content = format!(
        "# {}\n\n_Updated: {}_\n\n{}",
        model.topic,
        model.updated_at.to_rfc3339(),
        model.content
    );

    std::fs::write(&path, content).context("failed to write mental model file")?;
    Ok(())
}

/// Load a mental model from a markdown file, if it exists.
pub fn load_mental_model(dir: &Path, topic: &str) -> Result<Option<MentalModel>> {
    let filename = topic_to_filename(topic);
    let path = dir.join(format!("{filename}.md"));

    if !path.exists() {
        return Ok(None);
    }

    let raw = std::fs::read_to_string(&path).context("failed to read mental model file")?;
    let model = parse_mental_model_markdown(topic, &raw)?;
    Ok(Some(model))
}

/// Convert a topic string to a safe filename component.
fn topic_to_filename(topic: &str) -> String {
    topic
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .to_lowercase()
}

/// Parse a mental model markdown file back into a struct.
fn parse_mental_model_markdown(topic: &str, raw: &str) -> Result<MentalModel> {
    // Look for the updated timestamp line: _Updated: <rfc3339>_
    let updated_at = raw
        .lines()
        .find_map(|line| {
            let trimmed = line.trim();
            let inner = trimmed.strip_prefix("_Updated: ")?.strip_suffix('_')?;
            inner.parse::<DateTime<Utc>>().ok()
        })
        .unwrap_or_else(Utc::now);

    // Content is everything after the timestamp line (skip heading + blank + timestamp + blank)
    let content = raw
        .lines()
        .skip_while(|line| !line.starts_with("_Updated:"))
        .skip(1) // skip the timestamp line itself
        .skip_while(|line| line.trim().is_empty()) // skip blank lines after timestamp
        .collect::<Vec<_>>()
        .join("\n");

    Ok(MentalModel {
        topic: topic.to_string(),
        content,
        updated_at,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_save_and_load_mental_model() {
        let dir = TempDir::new().unwrap();
        let model = MentalModel {
            topic: "Auth Migration".to_string(),
            content: "The team decided to migrate from Auth0 to Clerk.".to_string(),
            updated_at: Utc::now(),
        };

        save_mental_model(dir.path(), &model).unwrap();
        let loaded = load_mental_model(dir.path(), "Auth Migration")
            .unwrap()
            .expect("model should exist");

        assert_eq!(loaded.topic, "Auth Migration");
        assert_eq!(
            loaded.content,
            "The team decided to migrate from Auth0 to Clerk."
        );
    }

    #[test]
    fn test_load_nonexistent_model_returns_none() {
        let dir = TempDir::new().unwrap();
        let result = load_mental_model(dir.path(), "Nonexistent").unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn test_topic_to_filename() {
        assert_eq!(topic_to_filename("Auth Migration"), "auth-migration");
        assert_eq!(
            topic_to_filename("security/auth patterns"),
            "security-auth-patterns"
        );
    }
}
